services:
  backupdb:
    build: .
    container_name: backupdb-go
    restart: unless-stopped
    ports:
      - "3400:3400"
    volumes:
      - ./data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3400/"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
